// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuCeP3SKqkkpV1CdEG4HThpxyG8OSTZ6c',
    appId: '1:1013926800665:web:4bb297e3a92297a4b46988',
    messagingSenderId: '1013926800665',
    projectId: 'beauty-salon-booking-6eefc',
    authDomain: 'beauty-salon-booking-6eefc.firebaseapp.com',
    storageBucket: 'beauty-salon-booking-6eefc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0aHB1b6RZ6A1KDSTtYfEF1-vN1SvOqJo',
    appId: '1:1013926800665:android:c6c0882a9ef02f29b46988',
    messagingSenderId: '1013926800665',
    projectId: 'beauty-salon-booking-6eefc',
    storageBucket: 'beauty-salon-booking-6eefc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzUm9JQBKX-FF0BYBTWhIB7gSUFVtePAQ',
    appId: '1:1013926800665:ios:9ca32c401e29e00eb46988',
    messagingSenderId: '1013926800665',
    projectId: 'beauty-salon-booking-6eefc',
    storageBucket: 'beauty-salon-booking-6eefc.appspot.com',
    iosBundleId: 'com.example.flutterBeautySalonBooking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzUm9JQBKX-FF0BYBTWhIB7gSUFVtePAQ',
    appId: '1:1013926800665:ios:e02ab48f34fd4fe5b46988',
    messagingSenderId: '1013926800665',
    projectId: 'beauty-salon-booking-6eefc',
    storageBucket: 'beauty-salon-booking-6eefc.appspot.com',
    iosBundleId: 'com.example.flutterBeautySalonBooking.RunnerTests',
  );
}
